[profile.default]
src = "contracts"
test = "forge-tests"
out = "out"
libs = ["lib", "node_modules"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 800
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
    "hardhat/=node_modules/hardhat/"
]
fs_permissions = [
    { access = "read", path = "./" },
    { access = "write", path = "./docs/deployments/kondux-batchminter" }
]
